/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package People;

import DB.DBConnection;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.util.regex.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nimesh
 */
public class Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    String eid;
    String ename;
    String position;
    String salary;
    String telno;
    String age;
    String email;
    String address;
    
    String sid;
    String sname;
    String company;
    String phone;
    String semail;
    String iname;
    String category;
    String noofitems;
    
    Connection con;
    
    private ImageIcon format = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;
    
    
    public Employee() {
        initComponents();
        con = DBConnection.connect();
        
        autoIDn();
        tableLordn();
        
        autoID();
        tableLord();
        
                
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public ImageIcon resizeImage(String imagePath, byte[] pic){
        ImageIcon myImage = null ;
        if(imagePath !=null)
        {
            myImage = new ImageIcon(imagePath);
        }
        else
        {
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblimage.getHeight(), lblimage.getWidth(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txteid = new javax.swing.JTextField();
        txtename = new javax.swing.JTextField();
        txttelno = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cmbposition = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        lbladd = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblupdate = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbldelete = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblclear = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblbrowse = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemp = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        txtcompany = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtiname = new javax.swing.JTextField();
        txtsemail = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cmbcategory = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtnoofitems = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lbladd1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblupdate1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbldelete1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblclear1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsup = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(680, 460));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel1.setText("Employee ID");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setText("Position");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel4.setText("Tel No.");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setText("Salary");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setText("E-mail");

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setText("Age");

        txteid.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        txtename.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtenameKeyReleased(evt);
            }
        });

        txttelno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txttelno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelnoKeyPressed(evt);
            }
        });

        txtage.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        txtsalary.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsalaryKeyPressed(evt);
            }
        });

        txtemail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        cmbposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Position", "Manager", "Executive", "Cashier", "Sale Boy" }));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setText("Address");

        txtaddress.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddressKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtename, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbposition, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 290));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 240));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbladd.setBackground(new java.awt.Color(153, 204, 255));
        lbladd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add");

        javax.swing.GroupLayout lbladdLayout = new javax.swing.GroupLayout(lbladd);
        lbladd.setLayout(lbladdLayout);
        lbladdLayout.setHorizontalGroup(
            lbladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbladdLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbladdLayout.setVerticalGroup(
            lbladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbladdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblupdate.setBackground(new java.awt.Color(153, 204, 255));
        lblupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblupdateMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update");

        javax.swing.GroupLayout lblupdateLayout = new javax.swing.GroupLayout(lblupdate);
        lblupdate.setLayout(lblupdateLayout);
        lblupdateLayout.setHorizontalGroup(
            lblupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblupdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblupdateLayout.setVerticalGroup(
            lblupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbldelete.setBackground(new java.awt.Color(153, 204, 255));
        lbldelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldeleteMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Delete");

        javax.swing.GroupLayout lbldeleteLayout = new javax.swing.GroupLayout(lbldelete);
        lbldelete.setLayout(lbldeleteLayout);
        lbldeleteLayout.setHorizontalGroup(
            lbldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbldeleteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        lbldeleteLayout.setVerticalGroup(
            lbldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbldeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblclear.setBackground(new java.awt.Color(255, 102, 102));
        lblclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclearMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clear");

        javax.swing.GroupLayout lblclearLayout = new javax.swing.GroupLayout(lblclear);
        lblclear.setLayout(lblclearLayout);
        lblclearLayout.setHorizontalGroup(
            lblclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblclearLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblclearLayout.setVerticalGroup(
            lblclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblclearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        lblbrowse.setBackground(new java.awt.Color(51, 204, 0));
        lblbrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbrowseMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Browse Image");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-24.png"))); // NOI18N

        javax.swing.GroupLayout lblbrowseLayout = new javax.swing.GroupLayout(lblbrowse);
        lblbrowse.setLayout(lblbrowseLayout);
        lblbrowseLayout.setHorizontalGroup(
            lblbrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblbrowseLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblbrowseLayout.setVerticalGroup(
            lblbrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblbrowseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblbrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblbrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbladd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbladd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 310, 290));

        tblemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblemp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 650, 90));

        jTabbedPane1.addTab("Employee", jPanel1);

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(680, 460));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel15.setText("Supplier ID");

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel17.setText("Company");

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel18.setText("Phone");

        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel20.setText("E-mail");

        jLabel21.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel21.setText("Item Name");

        txtsid.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        txtcompany.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtcompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompanyKeyReleased(evt);
            }
        });

        txtphone.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });

        txtiname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtiname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinameKeyReleased(evt);
            }
        });

        txtsemail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtsemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsemailKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel29.setText("Category");

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Laptops", "Processors", "Graphic Cards", "Power Supplies", "Storage", "Monitors", "Keybords & Mouse" }));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel16.setText("No. of Items");

        txtnoofitems.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtnoofitems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnoofitemsKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel30.setText("Supplier Name");

        txtsname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtsname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsnameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtiname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsemail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel15)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel29))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbcategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnoofitems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtsemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtnoofitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 290));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 240));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lbladd1.setBackground(new java.awt.Color(153, 204, 255));
        lbladd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladd1MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Add");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-24 1.png"))); // NOI18N

        javax.swing.GroupLayout lbladd1Layout = new javax.swing.GroupLayout(lbladd1);
        lbladd1.setLayout(lbladd1Layout);
        lbladd1Layout.setHorizontalGroup(
            lbladd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbladd1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbladd1Layout.setVerticalGroup(
            lbladd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbladd1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbladd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblupdate1.setBackground(new java.awt.Color(153, 204, 255));
        lblupdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblupdate1MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Update");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-update-24.png"))); // NOI18N

        javax.swing.GroupLayout lblupdate1Layout = new javax.swing.GroupLayout(lblupdate1);
        lblupdate1.setLayout(lblupdate1Layout);
        lblupdate1Layout.setHorizontalGroup(
            lblupdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblupdate1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        lblupdate1Layout.setVerticalGroup(
            lblupdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblupdate1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblupdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        lbldelete1.setBackground(new java.awt.Color(153, 204, 255));
        lbldelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldelete1MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Delete");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-bin-24.png"))); // NOI18N

        javax.swing.GroupLayout lbldelete1Layout = new javax.swing.GroupLayout(lbldelete1);
        lbldelete1.setLayout(lbldelete1Layout);
        lbldelete1Layout.setHorizontalGroup(
            lbldelete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbldelete1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbldelete1Layout.setVerticalGroup(
            lbldelete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbldelete1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbldelete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addContainerGap())
        );

        lblclear1.setBackground(new java.awt.Color(255, 102, 102));
        lblclear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclear1MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Clear");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-clear-symbol-26.png"))); // NOI18N

        javax.swing.GroupLayout lblclear1Layout = new javax.swing.GroupLayout(lblclear1);
        lblclear1.setLayout(lblclear1Layout);
        lblclear1Layout.setHorizontalGroup(
            lblclear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblclear1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblclear1Layout.setVerticalGroup(
            lblclear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblclear1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblclear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbladd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 310, 290));

        tblsup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsup);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 650, 90));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Supplier", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupMouseClicked

        String id;
        DefaultTableModel tmodel = (DefaultTableModel) tblsup.getModel();
        int selectrowindex = tblsup.getSelectedRow();
        id = (tmodel.getValueAt(selectrowindex, 0).toString());

        try {
            String sql = "SELECT `sup_id`, `sup_name`, `company`, `phone`, `email`, `item_name`, `category`, `no-of-items` FROM `supplier` WHERE sup_id= '" + id + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next())
            {
                txtsid.setText(rs.getString("sup_id"));
                txtsname.setText(rs.getString("sup_name"));
                txtcompany.setText(rs.getString("company"));
                txtphone.setText(rs.getString("phone"));
                txtsemail.setText(rs.getString("email"));
                txtiname.setText(rs.getString("item_name"));
                cmbcategory.setSelectedItem(rs.getString("category"));
                txtnoofitems.setText(rs.getString("no-of-items"));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_tblsupMouseClicked

    private void lbldelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldelete1MouseClicked

        try {
            String sql = "DELETE FROM `supplier` WHERE sup_id='" + txtsid.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.execute();
            tableLordn();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lbldelete1MouseClicked

    private void lblupdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblupdate1MouseClicked

        try {
            getdatan();
            String squpdate = "UPDATE `supplier` SET `sup_name`=?, `company`=?, `phone`=?, `email`=?, `item_name`=?, `category`=?, `no-of-items`=? WHERE sup_id ='" + sid+ "'";
            pst = (PreparedStatement) con.prepareStatement(squpdate);
            pst.setString(1, sname);
            pst.setString(2, company);
            pst.setString(3, phone);
            pst.setString(4, semail);
            pst.setString(5, iname);
            pst.setString(6, category);
            pst.setString(7, noofitems);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        clearDatan();
        tableLordn();
    }//GEN-LAST:event_lblupdate1MouseClicked

    private void lbladd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladd1MouseClicked

        getdatan();
        try {
            String q = "INSERT INTO `supplier`(`sup_id`, `sup_name`, `company`, `phone`, `email`, `item_name`, `category`, `no-of-items`) VALUES (?,?,?,?,?,?,?,?)";
            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setString(1, sid);
            pst.setString(2, sname);
            pst.setString(3, company);
            pst.setString(4, phone);
            pst.setString(5, semail);
            pst.setString(6, iname);
            pst.setString(7, category);
            pst.setString(8, noofitems);
            pst.execute();

            clearDatan();
            tableLordn();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        String sname = txtsname.getText();
        String company = txtcompany.getText();
        String phone = txtphone.getText();
        String semail = txtsemail.getText();
        String iname = txtiname.getText();
        String category = cmbcategory.getSelectedItem().toString();
        String noofitems = txtnoofitems.getText();

        
    }//GEN-LAST:event_lbladd1MouseClicked

    private void txtsnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsnameKeyReleased
        String PATTERN = "^[a-zA-Z][][a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtsname.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter a valid Name");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtsnameKeyReleased

    private void txtnoofitemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoofitemsKeyPressed

        String noofitems = txtnoofitems.getText();

        int length = noofitems.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<3){
                txtnoofitems.setEditable(true);
            }
            else{
                txtnoofitems.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                txtnoofitems.setEditable(true);
            }
            else{
                txtnoofitems.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtnoofitemsKeyPressed

    private void txtsemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsemailKeyReleased

        //email@gmail.com

        String PATTERN = "^[a-zA-Z]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtsemail.getText());
        if(!match.matches()){
            //JOptionPane.showMessageDialog(null, "Please Enter a valid Email");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtsemailKeyReleased

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        String phone = txtphone.getText();

        int length = phone.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                txtphone.setEditable(true);
            }
            else{
                txtphone.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                txtphone.setEditable(true);
            }
            else{
                txtphone.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtcompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompanyKeyReleased

        String PATTERN = "^[a-zA-Z][][a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcompany.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter a valid Company Name");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtcompanyKeyReleased

    private void tblempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempMouseClicked
        String id;
        DefaultTableModel tmodel = (DefaultTableModel) tblemp.getModel();
        int selectrowindex = tblemp.getSelectedRow();
        id = (tmodel.getValueAt(selectrowindex, 0).toString());

        try {
            String sql = "SELECT `emp_id`, `emp_name`, `tp_no`, `age`, `position`, `salary`, `email`, `address`, `image` FROM `employee` WHERE emp_id= '" + id + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next())
            {
                txteid.setText(rs.getString("emp_id"));
                txtename.setText(rs.getString("emp_name"));
                txttelno.setText(rs.getString("tp_no"));
                txtage.setText(rs.getString("age"));
                cmbposition.setSelectedItem(rs.getString("position"));
                txtsalary.setText(rs.getString("salary"));
                txtemail.setText(rs.getString("email"));
                txtaddress.setText(rs.getString("address"));

                byte[] imagedata = rs.getBytes("image");
                format = new ImageIcon(imagedata);
                Image mm = format.getImage();
                Image img2 = mm.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon (img2);
                lblimage.setIcon(image);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_tblempMouseClicked

    private void lblbrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbrowseMouseClicked
        JFileChooser fchoser = new JFileChooser();
        fchoser.showOpenDialog(null);
        File f = fchoser.getSelectedFile();
        fname = f.getAbsolutePath();
        ImageIcon micon = new ImageIcon(fname);
        try {
            File image = new File(fname);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte [] buf = new byte[1024];
            for (int readnum; (readnum = fis.read(buf)) !=-1;)
            {
                baos.write(buf, 0, readnum);
            }
            pimage = baos.toByteArray();
            lblimage.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {

            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_lblbrowseMouseClicked

    private void lblclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclearMouseClicked
        clearData();
    }//GEN-LAST:event_lblclearMouseClicked

    private void lbldeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseClicked
        try {
            String sql = "DELETE FROM `employee` WHERE emp_id='" + txteid.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.execute();
            tableLord();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lbldeleteMouseClicked

    private void lblupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblupdateMouseClicked

        try {
            getdata();
            String squpdate = "UPDATE `employee` SET `emp_name`=?, `tp_no`=?, `age`=?, `position`=?, `salary`=?, `email`=?, `address`=?, `image`=? WHERE emp_id ='" + eid+ "'";
            pst = (PreparedStatement) con.prepareStatement(squpdate);
            pst.setString(1, ename);
            pst.setString(2, telno);
            pst.setString(3, age);
            pst.setString(4, position);
            pst.setString(5, salary);
            pst.setString(6, email);
            pst.setString(7, address);
            pst.setBytes(8, pimage);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        clearData();
        tableLord();
    }//GEN-LAST:event_lblupdateMouseClicked

    private void lbladdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdMouseClicked

        getdata();
        try {
            String q = "INSERT INTO `employee`(`emp_id`, `emp_name`, `tp_no`, `age`, `position`, `salary`, `email`, `address`, `image`) VALUES (?,?,?,?,?,?,?,?,?)";
            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setString(1, eid);
            pst.setString(2, ename);
            pst.setString(3, telno);
            pst.setString(4, age);
            pst.setString(5, position);
            pst.setString(6, salary);
            pst.setString(7, email);
            pst.setString(8, address);
            pst.setBytes(9, pimage);
            pst.execute();

            clearData();
            tableLord();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        String ename = txtename.getText();
        String telno = txttelno.getText();
        String age = txtage.getText();
        String position = cmbposition.getSelectedItem().toString();
        String salary = txtsalary.getText();
        String email = txtemail.getText();
        String address = txtaddress.getText();
        String pimage = lblimage.getText();

        if(ename.equals("")){
            JOptionPane.showMessageDialog(null, "Name Can't be Empty!");
        }
        if(telno.equals("")){
            JOptionPane.showMessageDialog(null, "Tel No. Can't be Empty!");
        }
        if(age.equals("")){
            JOptionPane.showMessageDialog(null, "Age Can't be Empty!");
        }
        if(position.equals(0)){
            JOptionPane.showMessageDialog(null, "Select a Position!");
        }
        if(salary.equals("")){
            JOptionPane.showMessageDialog(null, "Salary Can't be Empty!");
        }
        if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Email Can't be Empty!");
        }
        if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Address Can't be Empty!");
        }
        if(pimage.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter an Image!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Validation Successful!");
        }
    }//GEN-LAST:event_lbladdMouseClicked

    private void txtaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyReleased

        String PATTERN = "^[a-zA-Z0-9][][/]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtaddress.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter a Address");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtaddressKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        //email@gmail.com

        String PATTERN = "^[a-zA-Z]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtemail.getText());
        if(!match.matches()){
            //JOptionPane.showMessageDialog(null, "Please Enter a valid Email");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaryKeyPressed

        String salary = txtsalary.getText();

        int length = salary.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<6){
                txtsalary.setEditable(true);
            }
            else{
                txtsalary.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                txtsalary.setEditable(true);
            }
            else{
                txtsalary.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtsalaryKeyPressed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        String age = txtage.getText();

        int length = age.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<2){
                txtage.setEditable(true);
            }
            else{
                txtage.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                txtage.setEditable(true);
            }
            else{
                txtage.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtageKeyPressed

    private void txttelnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelnoKeyPressed
        String telno = txttelno.getText();

        int length = telno.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                txttelno.setEditable(true);
            }
            else{
                txttelno.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                txttelno.setEditable(true);
            }
            else{
                txttelno.setEditable(false);
            }
        }
    }//GEN-LAST:event_txttelnoKeyPressed

    private void txtenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenameKeyReleased

        String PATTERN = "^[a-zA-Z][][a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtename.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter a valid Name");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_txtenameKeyReleased

    private void lblclear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclear1MouseClicked

        clearDatan();
        
    }//GEN-LAST:event_lblclear1MouseClicked

    private void txtinameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinameKeyReleased
        
        String PATTERN = "^[a-zA-Z0-9][][a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtiname.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter a valid Item Name");
        }
        else{
            //JOptionPane.showMessageDialog(null, s);
        }
        
    }//GEN-LAST:event_txtinameKeyReleased

    //Employee
    private void tableLord()
    {
        try {
            String sql = "SELECT `emp_id`, `emp_name`, `tp_no`, `age`, `position`, `salary`, `email`, `address`, `image` FROM `employee`";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblemp.setModel (net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    
    private void clearData()
    {
        autoID();
        txtename.setText("");
        txttelno.setText("");
        txtage.setText("");
        cmbposition.setSelectedIndex(0);     
        txtsalary.setText("");
        txtemail.setText("");
        txtaddress.setText("");
    }
    
    private void getdata()
    {
        eid = txteid.getText();
        ename = txtename.getText();
        telno = txttelno.getText();
        age = txtage.getText();
        position = cmbposition.getSelectedItem().toString();       
        salary = txtsalary.getText();
        email = txtemail.getText();
        address = txtaddress.getText();
    }
    
    private void autoID()
    {
        try {
            String sql = "SELECT `emp_id` FROM `employee` ORDER BY emp_id DESC LIMIT 1";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                String rnno = rs.getString("emp_id");
                int co = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                txteid.setText(ftxt);
            }
            else
            {
                txteid.setText("EID100");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
                
    }
    
    
    //Supplier
    private void tableLordn()
    {
        try {
            String sql = "SELECT `sup_id`, `sup_name`, `company`, `phone`, `email`, `item_name`, `category`, `no-of-items` FROM `supplier`";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblsup.setModel (net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    
    private void clearDatan()
    {
        autoIDn();
        txtsname.setText("");
        txtcompany.setText("");
        txtphone.setText("");
        txtsemail.setText("");
        txtiname.setText("");
        cmbcategory.setSelectedIndex(0);
        txtnoofitems.setText("");
    }
    
    private void getdatan()
    {
        sid = txtsid.getText();
        sname = txtsname.getText();
        company = txtcompany.getText();
        phone = txtphone.getText();
        semail = txtsemail.getText();
        iname = txtiname.getText();
        category = cmbcategory.getSelectedItem().toString();
        noofitems = txtnoofitems.getText();
    }
    
    private void autoIDn()
    {
        try {
            String sql = "SELECT `sup_id` FROM `supplier` ORDER BY sup_id DESC LIMIT 1";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                String rnno = rs.getString("sup_id");
                int co = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                txtsid.setText(ftxt);
            }
            else
            {
                txtsid.setText("SID100");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbposition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel lbladd;
    private javax.swing.JPanel lbladd1;
    private javax.swing.JPanel lblbrowse;
    private javax.swing.JPanel lblclear;
    private javax.swing.JPanel lblclear1;
    private javax.swing.JPanel lbldelete;
    private javax.swing.JPanel lbldelete1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPanel lblupdate;
    private javax.swing.JPanel lblupdate1;
    private javax.swing.JTable tblemp;
    private javax.swing.JTable tblsup;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtename;
    private javax.swing.JTextField txtiname;
    private javax.swing.JTextField txtnoofitems;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsemail;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsname;
    private javax.swing.JTextField txttelno;
    // End of variables declaration//GEN-END:variables
}
